LukeSmithxyz/based.cooking

src/portuguese-steak-with-beer-sauce.md

Corrected the spelling error on "ingredients", and also added a link reference to rice.

Fix spelling error and linked other articles

---

src/rice.md

Fix small typo in rice.md

---

src/french-mustard-sauce-porkchops.md
src/index.md

Also added my previous recipe in the index file

add french mustard porkchops

---

src/almeirim-stone-soup.md

Includes the famous tale of the stone soup, I can remove if it's too much.

Adding Almeirim Stone Soup recipe

---

src/_header.html

Small change -- big difference.

Make the site scale properly on mobile

---

src/chicken-tacos.md
src/eggs.md
src/french-mustard-sauce-porkchops.md
src/gnocchi.md
src/index.md
src/mortar-and-pestle.md
src/pasta.md
src/salt.md

I was working on this PR when #23 was made, and this one fixes more.
P.S.
I suggest people should configure vim to have spell check for markdown files.

Fix spelling errors

---

src/style.css

Now the font is not completly on the edge of the browser's frame.

added litte bit of padding

---

src/chicken-wings.md
src/index.md
src/template.md

- Simple chicken wing recipe that never fails
- Fix some typos in the template

Chicken wings

---

src/almeirim-stone-soup.md

So people won't have to scroll down for the Ingredients and Directions

Story moved to below Directions

---

src/dried-tomato-plum-spread.md
src/index.md

Ima join the meme.
Either way here's a cool recipe for a bread spread.

Add dried tomato and plum spread

---

src/eggs.md

I'm not perfect at writing but if you follow the instructions as intended the eggs come out great.

Fluffy scrambled eggs

---

src/chicken-parmesan.md

Fix broken link for pasta

---

src/drunken-beans.md
src/index.md

adding drunken-beans.md

---

src/almeirim-stone-soup.md
src/portuguese-steak-with-beer-sauce.md

Use ordered, not unordered, lists

---

src/miso_ginger_pork.md

love your idea here... I'll contribute when I can

miso ginger pork

---

src/index.md
src/liverpate.md

Add liverpate

---

src/chicken-biscuit-potpie.md
src/index.md

Chicken biscuit potpie recipe.

Added chicken biscuit potpie recipe.

---

src/aelplermagronen.md
src/index.md

Wanted to contribute with one of my favorite recipes.
`index.md` seems to be just chronological for now, right? I just appended mine at the bottom.

Add Älplermagronen

---

src/flammkuchen.md
src/index.md

A recipe for flammkuchen - will provide pictures after next cooking :)

Flammkuchen

---

src/banana-muffins-with-chocolate.md
src/index.md

I hope it's not too "hyper-sugary." Those are good muffins.

Add a recipe for banana muffins with chocolate.

---

src/index.md
src/ragu.md

adding to ragu to the index and other suggested fixes

ragu fixes

---

src/_header.html

If you're submitting a recipe, remember to:
1. Add it to the index
2. Follow all [submission guidelines](https://github.com/LukeSmithxyz/based.cooking#rules-for-submission)
(feel free to remove this text from your PR once you've reviewed the checklist)

Lang attribute was not properly closed

---

src/index.md

Was trying to add earlier today but kept getting error.

Add recipe to index.md

---

src/index.md
src/roesti.md

Don't have a good picture for now. Will add one after lent.

[ADD] Rösti recipe

---

src/miso-ginger-pork.md

fixed typos & added metric units to Miso-Ginger-Pork

---

src/caesar-salad.md

There were typos in the word `parmesan`.

Fixed typos in caesar salad recipe

---

src/chicken-biscuit-potpie.md
src/matcha-cookies.md
src/scandinavian-coffee-cake.md
src/sweet-potato-fries.md
src/tuscan-style-pork-roast.md
src/yogurt.md

Based on #49, I manually add some measures that were specific to a metric system.
Haven't put much thought on converting other measurements though.

Add converted measurements

---

src/index.md
src/quesadilla.md

add quesadilla.md to src

---

src/index.md

Fix missing link for tuna-sub

---

src/cacio-e-pepe.md
src/caesar-salad.md
src/chicken-parmesan.md
src/chicken-tacos.md
src/chicken-wings.md
src/chili-con-carne.md
src/country-skillet.md
src/croutons.md
src/drunken-beans.md
src/fried-anglerfish-fillet.md
src/fried-potatoes.md
src/index.md
src/japanese-noodle-soup.md
src/ketchup.md
src/matcha-cookies.md
src/miso-ginger-pork.md
src/pancake.md
src/pork-based-chili-con-carne.md

Spelling and formatting fixes

---

src/index.md

Added Ginataang Kalabasa to index.md

---

src/index.md

Added hummus to index.md

---

src/index.md

Added peanut butter to index.md

---

src/index.md
src/spaghetti-and-meatballs.md

Spaghetti and Meatballs recipe

---

src/index.md

Added Hellfire Steak to index.md

---

src/index.md
src/simple-sauce.md

This is a simple sauce. Most people know how to make it, and it is a base for other sauces, like '1000 island sauce'. It also makes a really good dip for potato chips and other things.

Added a simple sauce.

---

src/cacio-e-pepe.md
src/fried-anglerfish-fillet.md

Two src files needed clean up, as shown.

File maintenance

---

Makefile

fix RSS titles, put whole recipe in description

---

src/breton-crepes.md
src/french-crepes.md

French traditional crepe (dessert or dish)

French crepes recipe

---

src/butter-chicken-masala.md
src/naan-bread.md

recipe added : butter chicken and naan

---

src/fish-curry.md
src/tomato-and-grilled-paprika-soup.md
src/zopf.md

Add fish curry, Zopf and Tomato / Bell pepper soup

---

src/banana-green-smoothie.md
src/mango-banana-smoothie.md

Added banana green and mango banana smoothie recipe

---

src/tuna-salad.md

added tuna salad

---

src/gumbo-shrimp-and-sausage.md

added gumbo recipe

---

src/coconut-oil-coffee.md
src/gloomy-day-smoothie.md
src/party-mimosa.md

added party mimosa, coconut oil coffee and gloomy day smoothie recipe 

---

src/lemon-juice-salad-dressing.md

Add salad dressing

---

src/tomato-flavored-hamburger-macaroni.md

Fixed spelling mistakes in TFHM

---

src/brigadeiro.md

Add brazilian brigadeiro

---

src/chicken-soup.md
src/pickled-onions.md

Add Chicken Soup and Pickled Onions recipes

---

src/pilaf.md
src/plov.md

Added Plov or Pilaf or Pilau

---

src/dominican-spaghetti.md

added dominican spaghetti recipe

---

src/cannellini-bean-salad.md

added cannellini bean salad recipe

---

src/baked-salmon.md

added salmon recipe

---

src/fajita-seasoning.md

added fajita seasoning recipe

---

src/cooked-chickpeas.md

added chickpea recipe

---

src/danish-pancake.md

Add Danish Pancake Recipe

---

src/potato-leek-soup.md

A simple recipe for potato leek soup. :)

added potato leek soup recipe

---

src/shrimp-and-grits.md

added shrimp and grits recipe

---

src/danish-pancake.md

spellin-fix

---

src/salsa-verde.md

add salsa verde

---

src/bloody-mary-mix.md
src/irish-coffee.md
src/kale-banana-smoothie.md
src/orange-glorious.md
src/peanut-butte-banana-smoothie.md

added irish coffee, kale banana smoothie, bloody mary mix, orange glorious and peanut butter banana smoothie recipe

---

src/hamburger-patties-all-beef.md

Adding all-beef patties

---

src/baked-salmon.md

Add degrees Celcius

---

src/chimichanga.md

Add Chimichanga

---

src/cacio-e-pepe.md

I fixed the recipe for Cacio e Pepe to reflect the original one.

fixed Cacio e Pepe recipe

---

README.md

webm -> webp in readme.md

---

src/banana-pancakes.md
src/oaty-pancakes.md
src/pancake.md

As the danish pancake had the pancake tag, I felt like it would be useful to have the other pancake recipes also under the tag

Adds pancake tag to pancake recipes missing the tag

---

src/brigadeiro.md

1. Added one more tag
2. Added optional step
3. Fixed some grammer

A quick modification

---

example.md

typo fix in example.md

---

README.md

reciples --> recipes
Just decided to fix a spelling mistake I noticed

Correct minor spelling mistake

---

src/schinkenfleckerl-gratinated

Initial commit

---

src/aglio-e-olio.md
src/mushroom-risotto.md

Added Mushroom Risotto Recipe

---

src/brigadeiro.md

Fixing some mistakes in the brigadeiro recipe

---

src/babas-feta-pasta.md

Add Baba's Feta Pasta (Will add image next time I make it)

---

src/chicken-tacos.md
src/pork-carnitas.md

there are no tags for slow-cooked but there's precedent for stylizing it as `slow-cooked` [here](https://based.cooking/chicken-tacos) (where i've also added that tag)

added pork carnitas & slow-cooked tag

---

src/pizza-dough.md

Fix typos for Pizza Dough recipe

---

src/cheesy-potatoe-bake.md

Added a cheesy potato bake recipe

---

src/simple-chicken-curry.md

Add Simple Chicken Curry

---

src/cheesy-pasta-bake.md

Let me know if you need me to edit anything, but I think I followed all the rules correctly.

Added Cheesy Pasta Bake

---

src/breakfast-wrap.md

Add Breakfast Wrap

---

src/kalderetang-manok.md

Added kalderetang manok recipe.

---

src/loaded-mexican-rice.md

loaded-mexican-rice

---

src/stoemp.md

add stoemp

---

src/Lasagna.md
src/lasagna.md

thought based.cooking needed a lasagna recipe. <3

Created Lasagna.md

---

src/spanish-tortilla.md

Previously had an incorrect space in markdown contribution link, removed this and link displays as intended in markdown.

Fix Spanish tortilla markdown link

---

src/spanish-tortilla.md

Previously its tag was "egg", this created a new "egg" category, rather than adding it to the per-existing "eggs" category

Move Spanish tortilla into eggs category

---

src/kvass.md

[Kvass](https://en.wikipedia.org/wiki/Kvass) is a Slavic fermented beverage which is both simple to make and rich in flavour.

Add recipe for kvass

---

templates/header.html

This will get the site a better SEO score in Lighthouse. I believe it's used by search engines to show a description for the site? Good nonetheless. (if it should be changed lemme know)

add meta description tag

---

src/nashville-chicken.md

Currently the link is not legal markdown, this keeps the link and text the same but is legal markdown.

Format contribution link with markdown

---

src/francesinha.md

Added Francesinha recipe

---

.github/workflows/pr.yaml
.github/workflows/scripts/check-size.sh

Workflow to check images size in PR

Add images size checking in PR

---

src/japanese-noodle-soup.md

Japanese Noodle Soup: Align items in list

---

example.md

Inline "Cook time"

---

src/crab-salad.md

Add Recipe for Crab salad

---

.github/workflows/scripts/check-files.sh

Made some mistakes that @danielleontiev found in my last PR. This is to fix those.
I noticed that actually at any point if something fails that it wouldn't check the rest of the files, so I removed the exit commands and we now exit once at the end of all the files depending on if we had any failures.

Fixed some issues from last PR #400

---

src/glutenfree-pfannkuchen.md

Glutenfree Pfannkuchen: Correct tags format

---

src/pan-pizza.md

Add picture to recipe

---

src/glutenfree-pfannkuchen.md

removed commas in tag section for glutenfree-pfannkuchen

removed commas in tag section

---

src/bolo-do-caco.md

Hello, added a really good bread recipe from the island I live in Portugal. Hope you like it!

Bolo do caco recipe added 🇵🇹

---

src/eggroll-in-a-bowl.md

add eggroll in a bowl recipe

---

src/miso-soup.md

add miso-soup.md

---

index.md

using "via" twice in the same breath is strange

better wording

---

src/simple-pasta-cream-sauce.md

Simple pasta cream sauce, I guess someone could change the ingredients to match the US names for dairy.

Add Recipe for Creamy Pasta Sauce

---

data/style.css

Made the color scheme (of dark mode specifically) a bit easier on the eyes.
I felt the old color scheme contrasted a bit too much so I thought i would change it 
Heres an image, on the left you can see my version, and on the right you can see the default version.

Made the (dark mode) color scheme easier on the eyes

---

src/garlic-toast.md

Added simple recipe for garlic toast. Currently no photos, can add some in about a week.

Add recipe for garlic toast

---

src/brown-sauce.md
src/pepper-sauce.md
src/sourdough-starter.md

- Sour dough starter recipe for all sour dough baking
- Basic pepper sauce recipe
- Basic brown sauce recipe

few recipes: sour dough starter, pepper sauce and brown sauce

---

src/tiroler-grostl.md

I'm not from Austria, maybe there are locals from Tirol that can improve
on this already delicious recipe?

Add recipe for Tiroler Gröstl.

---

src/erwtensoep.md

Add Erwtensoep (Dutch pea soup) recipe

---

src/brigadeiro.md

When you start mixing a brigadeiro it is already sticking to the bottom of the pan (It's basically condensed milk and butter).
Only when it STOPS sticking to the pan it is ready.

Fixing brigadeiro (again?)

---

templates/header.html

Fix meta closing tag

---

src/fondue.md

Add fondue recipe

---

src/turkish-yogurt-soup.md

Add Turkish Yogurt Soup recipe

---

src/carbonara.md

As an italian i'm highly concerned about the use of sausage, you would do that as a last resort, same thing with linguine it's not the true thing.
However i added the options of Parmigiano and Smoked Pancetta ( i know it's controversial but at least not as much as sausage)
Also did some further changes to the preparation, adding time and adjusted ingredients and serving for 4 persons.

Removing sausage and adding some details

---

src/aglio-e-olio.md

Added cook time to aglio-e-olio.md

---

src/chicken-stock-bone-broth.md

Fix typo "along" to "alone"

---

src/carbonara.md

Fix Redirect

---

src/basic-meatballs.md

Included a basic meatball recipe I modified from some others I found on blogs and in J Kenji Lopez Alt's "Food Lab".

Added Basic Meatball Recipe

---

src/demi-glace.md

This is an incredibly based basic almost instant demi-glace recipe that is meant to be used in other incredibly based pan sauce recipes.

Add demi-glace recipe

---

src/spicy-mayo.md

added spicy mayo recipe

---

src/shepherds-pie.md

A nice shepherds pie recipe which is relatively easy to make

Shepherds Pie

---

src/cacio-e-pepe.md

The water added to the pecorino should be pasta water

Minor correction to cacio e pepe recipe

---

src/cole-slaw.md

Adding cole slaw recipe

---

src/aglio-e-olio.md
src/babas-feta-pasta.md
src/baked-mostaccioli.md
src/cacio-e-pepe.md
src/cheesy-pasta-bake.md
src/chicken-pasta-casserole.md
src/cinque-pi.md
src/dominican-spaghetti.md
src/pasta-alla-norma.md
src/pasta-navy-style.md
src/ragu.md
src/spaghetti-all-amatriciana.md
src/spaghetti-alla-puttanesca.md
src/spaghetti-and-meatballs.md

Link pasta recipe where appropriate

---

src/coriander-chicken.md

Added a recipe for coriander chicken.

Added coriander chicken recipe

---

src/aljotta.md
src/pate-chinois.md
src/stoemp.md
src/zarangollo.md

Deduplicate and de-typo a couple tags

---

src/broiled-trevally.md

"morter and pestle, of course" is linked to mortar-and-pestle.html, which doesn't seem to exist.

removes broken link

---

src/ukrainian-borscht.md

Ukrainian Borscht recipe

---

src/okonomiyaki.md

Japanese Okonomiyaki pancake

---

src/mazurek.md
src/orange-jam.md

Still time to make this for the second day of Easter!
Split into to recipes since the jam topping is a generic spread that can be used on its own/with other recipes.

Add mazurek

---

src/ukrainian-vareniki.md

Added Ukrainian Vareniki recipe

---

src/italian-bread.md

Add Italian Bread

---

src/babas-feta-pasta.md

Changed 'credit' to 'contribution'

---

src/challah-bread.md

A kind of braided bread preperation.

challah-bread

---

src/no-knead-bread.md

Fixed a link on no-knead bread recipe.

Fixed link

---

src/yibin-burning-noodles.md

This is a recipe I saw on [YouTube](https://www.youtube.com/watch?v=A1y-OhS9z20) and also read about on [The Mala Market](https://blog.themalamarket.com/yibin-ran-mian-burning-noodles-from-yibin-sichuan/). I've simplified, standardised and consolidated the recipe for this project.

Add Yibin Burning Noodles Recipe

---

src/australian-snags.md

Australian snags (Sausages sizzle)

---

README.md

'the top, not trailing line at the end.' to 'the top, no trailing line at the end.'

Fixed spelling.

---

src/coriander-chicken.md
src/garam-masala.md

Changing the donation methods and adding a link with more methods

Adding new donation method

---

src/honey-garlic-chicken.md

Added honey garlic chicken with brown rice and broccoli dish.

Honey Garlic Chicken

---

src/chorizo-and-chickpea-soup.md

Escaped ampersand to address issue #630

Escaped ampersand

---

src/baby-back-ribs

Add baby-back-ribs.md

---

src/full-english-breakfast.md

Adding a full English breakfast

---

src/tzatziki

Checked and ready to be merged

Tzatziki Spread

---

content/cheese.md
content/cream-cheese.md
content/greek-yogurt.md
content/milk-ricotta.md
content/whey-ricotta.md

Chese and other kinds of milk derivatives are often not only recipes by themselves, but also dependacies for other recipes.
This is the first load of recipes for milk derivatives, I might add more in the future, if it is appropriate.

Added recipes for cheese, ricotta (from both milk and whey), cream cheese, and greek yogurt

---

content/chicken-tenders-airfried.md

add space after ":"

---

src/spicy-sausage-pasta.md

added spicy sausage pasta recipe

---

content/no-knead-bread.md

It seems as though merge info was left behind, just cleaning it up.

Remove git merge info from no-kneadbread.md

---

content/tzatziki.md

Ingredients listed logically and semi-alphabetically. Directions grouped to reduce cognitive load.

Improve readability

---

content/_index.md
static/style.css

* clean up javascript
* set element id instead of class on the `clear-search` button

clean up js

---

content/_index.md

I don't know who introduced the `let matchCount = 0;` line again

clean up again & just compute searchText.split(" ") once

---

static/style.css

Your commit 5e3b7c54e7263f3d3ab659b35302489d161a5392 "replaced" `list-item`(li's default) with `block`, and I think that it was not intentional. If it was, close this.

make search results numbered

---

static/style.css

* fix hover on visited links (move :hover after :visited selector)
* add underline when hovering links (accessibility)

fix hover on visited links & add underline when hovering links

---

content/chicken-satay.md

This is a recipe for a Thai chicken satay with peanut sauce.

chicken satay

---

content/seafood-pasta.md
data/authors/nelson-morrow.json

Cooked this recipe last night and didn't find anything like it on the site. Thanks!

Garlic Butter Seafood Pasta

---

content/pulpo-gallega.md

Fix broken image of pulpo gallega recipe

Fix image of pulpo gallega

---

content/chipolata-in-balsamic-vinegar

Add recipe chipolata-in-balsamic-vinegar

---

content/farci-tomatoes.md

There's no reason why these should be separate tags

Change "tomatoes" tag to "tomato"

---

content/autumn-soup.md
content/greek-salad.md
content/gypsy-soup.md
content/ratatouille.md
content/red-lentil-dahl.md
content/shrimp-and-chicken-jambalaya.md
content/spinach-rice-casserole.md
data/authors/joel-maxuel.json

Includes profile. No pictures yet.

Adding first seven recipes

---

data/authors/elias-howell.json

updating the url for my website

update my website url

---

layouts/_default/single.html
layouts/partials/contributor.html

move contributor part to partial file

clean single.html

---

data/authors/elias-howell.json

issues with domain provider transfers, changing providers, etc.
this is the final url update for my website

update url... again

---

layouts/shortcodes/crypto.html
static/style.css

Aligned the crypto QR codes seen on the main page.
Also added some padding to the images so that they don't touch the line at the bottom or the addresses.

Fix crypto QR alignment

---

content/autumn-soup.md

There is no reason to make them as separate tags

Change "vegetable" tag to "vegetables"
