src/index.md
Oddly enough, the recipe that started this very site was missing on the index.
=> Added Chicken Parmesan and Bitoque

src/index.md
Previously linked to lukesmithxyz/based.recipes, which does not exist.
=> Fix GitHub url on homepage

src/.ssgignore, src/example.md
https://based.cooking/template.html should no longer be generated.
Also, removed example.md since it looked like a leftover from testing.
=> Add .ssgignore and ignore template.md

src/style.css
Removes the blue colour and underlining from hyperlinks when printing the page.
before: [http://0x0.st/-ZBB.pdf](http://0x0.st/-ZBB.pdf)
after: [http://0x0.st/-ZjZ.pdf](http://0x0.st/-ZjZ.pdf)
=> Remove hyperlinks when printing

src/matcha-cookies.md
Ingredients weren't in an unordered list. Rendered them as one long line.
Seems like I also deleted some trailing whitespaces.
=> Fixes matcha cookies listing

.github/pull_request_template.md
This will place a reminder to review submission guidelines (in particular, to add one's recipe to the index) when creating a PR.
=> Add PR template with index reminder

.github/workflows/upload.yml
I'm pretty sure the `on: pull_request` event means deployments would be attempted from each PR, even before they're merged into master. Just having `on: push` should capture both direct pushes and PR merges to master. [Reference](https://stackoverflow.com/a/61565445/7406283).
=> Disable deployments on PR creation

src/japanese-noodle-soup.md, src/sticky-porkchops.md
=> fixed sticky pork hyperlink issue from japanese noodle soup and replaced duplicate description

Makefile
Links in RSS feed look like:
`https://based.cooking//spatchcock-chicken.md.html`.
This commit corrects them to:
`https://based.cooking/spatchcock-chicken.html`.
=> Fix rss links

data/style.css
The `li img` selector looks like it was meant to target the bitcoin and monero icons on the homepage, but it is also targeting images that people have put at certain steps of recipe directions.
I have Updated the css selector to be more specific so that it won't target directional images on recipe pages anymore.
Example page: https://based.cooking/stuffed-round-squash (note the really small images at the end of directions 1 and 2).
=> Fixed Image sizing for directional images

src/fish-curry.md, src/tomato-and-grilled-paprika-soup.md, src/zopf.md
Someone had a broken link - without the protocol specifier, browsers interpret it as a relative link.
=> Fix relative link

src/gnocchi.md
"Parmesan" is a generic name for the cheese Parmigiano-Regiano. I propose instating the rule that this traditional, authentic cheese must always be preferred over the cheaper, mass-produced "parmesan".
Please see: https://en.wikipedia.org/wiki/Parmigiano-Reggiano
=> Correct grammar and name

Makefile
Allow punctuation signs to separate tags instead of just space.
Some people understandably made the mistake of separating tags by commas, thus creating new duplicate tags with the comma in it.
This commit `tr` all punctuation into spaces to avoid this, easier than enforcing another formatting rule onto authors.
=> consolidate tag parsing

src/hummus.md
TBH the previous recipe for hummus is not good. When using canned chickpeas, they need to be boiled for about 20 minutes or they won't blend uniformly and you'll end up with little hard bits in the hummus, and it won't whip up and increase in volume properly. If you take this step you can also skip removing the skins, as the baking soda and boiling time breaks them down enough that they disappear completely while blending. The previous recipe didn't include enough tahini, and didn't give useful guidelines for how much lemon juice and olive oil to use, and also skipped the garlic completely.
=> Revise hummus recipe

src/cinque-pi.md
Tags current use ', ' as a seperator, this works, but changing to ' ' brings in line with the rest of the site.
=> Format Cinque Pi tags properly

src/baked-mostaccioli.md
Tags current use ', ' as a separator, this works, but changing to ' ' brings in line with the rest of the site.
=> Format Baked Mostaccioli tags properly

templates/header.html
Browser will query for a `favicon.ico` if none were specified.
Using emoji and SVG we can create a **very light** favicon that is still descriptive of the website and avoid having one more request done to the server for nothing.
=> Add a lightweight inline favicon

Makefile
See issue #354. A tag page like `cake` was also using recipes tagged as `pancake` because it contained the word `cake`. Since some pancake recipes were also tagged as cake, they appeared twice.
Solution was to specify that grep look for a line that is the name of a tag, instead of seeing if the line contains the name of a tag.
=> Fixes duplicates on tag pages (#354)

Makefile
Consider this [chicken-tacos](https://based.cooking/chicken-tacos) recipe.
it has the `slow-cooked` tag on it. But if you click the tag on this page you get taken to a page that doesn't exist because the tagging separates on punctuation, which includes hyphens. So you actually end up with this recipe in a tag called `slow` and a tag called `cooked`.
I changed the `tr` command to use the `-c` option for the complement of SET1, and SET1 is now alpha characters and hyphens. So now tags will be split on characters that aren't alpha or hyphens, which should work for any case we have.
I decided not to do capital letters, because tags shouldn't be capitalized anyways.
=> Fix tag separator to allow hyphen separated tags like 'slow-cooked'

src/scandinavian-coffee-cake.md
Fixed a stray unordered list asterisk, which caused the `## Ingredients` header to render with a bullet point. Now there's a blank line between the first unordered list and the header.
=> Fixed Scandinavian coffee cake recipe formatting error

src/tuhu.md
Tuh'u (Akkadian for possibly "beetroot") is an ancient Mesopotamian spring festival dish, a lamb stew of sorts, extracted by historians at Yale Babylonian Collection from tablets from Babylonia, ca. 1740 BC.
=> Add recipe for tuhu

.github/workflows/scripts/check-files.sh
I've added some improvements and changes to the PR script. I will explain my changes here:
- Because of  `set -eu`, I can't `exit 1` inside awk because that causes the awk command to fail, which will immediately exit the script. Instead of exiting with an error code inside awk, I just capture the output of awk, and if it isn't empty print all those messages out and set the `FAIL` flag.
- I added a check to the awk command to check for consecutive empty lines since that is something that sometimes comes through PRs
- I changed the `/^# Ingredients` and the directions regexes to check the whole line literally instead, otherwise extra words or the line ending with `:` would get passed.
- Added a check to the awk command to check that the list of tags is only lowercase letters and hyphens
- I …
=> Improved the PR check script

.github/workflows/upload.yml
Initially, I made blogit to clean everything before rebuilding because the Makefile was still being modified (and rebuild is not triggered by a Maekfile modif). NMow, with the growing number of recipes, it's time to use the Makefile in all its glory and let it decide for itself what to rebuild.
=> gotta go fast: don't clean before building

src/garlic-toast.md
Clarifies the use of aluminum foil in this case. For a crispy garlic toast, use foil to line tray. Original recipe could imply covering the toast with foil, which is a valid way to make soft garlic bread, but it does seem that the rest of the recipe is implying the goal is to make the crispy version.
=> Clarify the use of aluminum foil on the tray.

src/tiroler-groestl.md
fixed umlaut in filename
added missing potato tag
=> austrian autism

templates/header.html
Current favicon size clips and gets cropped in certain browsers.
This change decreases the size slightly.
=> Reduce favicon emoji size 90 -> 80

src/croutons.md
While yes, 350 °F is technically only 176 °C, no Celsius-based oven has such a setting, and the closest one is 180 °C.
=> Add Celsius amount to the crouton recipe

src/no-knead-bread.md
Substantially decreased amount of salt in no-knead bread recipe from the ludicrous 1 and a quarter tablespoons to a reasonable 1 teaspoon.
Changed water from "1 + 1/2 + 1/8" cups of hot water to a simpler "1 1/2" cups of warm water (Hot will kill the yeast) as the extra 1/8th cup is not needed.
Added "or until doubled" to the end of line 20 as often 12 full hours of rising is not needed.
=> Decreased salt and water in no-knead-bread.md

static/style.css
While shopping for recipes I noticed that longer names would overflow into the next list item on my cell phone, which was quite annoying.
I fixed the issue by using padding and inline-block instead of the height and block properties of the li>a inside the pointer media query.
I was able to replicate this problem on Firefox Android (12) and chromium-101 (use dev tools to select a mobile viewport; if you click on the "select an element...." button the problem will disappear - no idea why).
Cheers
=> Fix overlap in recipe list on small devices

config.toml, content/_index.md, layouts/shortcodes/artlist.html, static/style.css
This PR is from @omar2205 and #533 updated for the Hugo site.
The number of articles is becoming unwieldy and it'd be nice to filter them quickly. This is theoretically what Javascript *should* be doing.
I almost want to merge this as is, but there are a few improvements I want, but I don't know how to best do them in JS.
1. Right now, the user has to type in the search bar and press enter to filter articles. I would like to remove the enter step and have them filter real-time.
2. I'd like to use JS to display the filtered articles larger, i.e. change CSS. I don't know how to do this.
3. Note that I've removed the tag/category list with this PR, but I'd like suggestions of what to do here as well. Categories still display at the end of each recipe, but I feel like there should be a …
=> Filter Articles with a Javascript Search

content/_index.md, layouts/shortcodes/artlist.html
When storing metadata in an HTML node, you can use data attributes, which is more declarative, and doesn't require rendering an invisible node.
See: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
=> Replace "style=display:none" with HTML data tags

content/_index.md
Normalizes search text and recipe title/tags so that both the name with the accent included and without accent will find the correct recipe. A search input of "crêpe" will be turned into "crepe". While as previously only searching "crêpe" will find the crepe recipes.
=> remove accents from search input and search string

content/korv-stroganoff.md
*Korv* is a word from Swedish meaning sausage. The title contains *Korv* so I thought the `sausage` tag would be good.
=> Add the sausage tag to Korv Stroganoff
